import { useCallback, useEffect, useState } from 'react';
import type { Todo } from '@todo/contracts';
import { ApiClientError } from '../../api/apiClientError.js';
import { todoApiClient } from '../../api/todoApiClient.js';
import { validateTitle } from './todoValidation.js';
import './styles.css';

const sort=(items:Todo[])=>[...items].sort((a,b)=>Number(a.completed)-Number(b.completed)||b.createdAt.localeCompare(a.createdAt));
export function TodoPage(){const [items,setItems]=useState<Todo[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [title,setTitle]=useState('');const [notice,setNotice]=useState('');const [editing,setEditing]=useState<string|null>(null);const [editTitle,setEditTitle]=useState('');const [deleting,setDeleting]=useState<Todo|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(sort(await todoApiClient.list()));}catch(e){setError(e instanceof Error?e.message:'读取失败，请稍后重试');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const saveNew=async(e:React.FormEvent)=>{e.preventDefault();const msg=validateTitle(title);if(msg){setError(msg);return;}try{const item=await todoApiClient.create(title);setItems(v=>sort([item,...v]));setTitle('');setError('');setNotice('已保存');}catch(e){setError(e instanceof Error?e.message:'保存失败，请稍后重试');}};
 const update=async(item:Todo,patch:Parameters<typeof todoApiClient.update>[1])=>{try{const updated=await todoApiClient.update(item.id,patch);setItems(v=>sort(v.map(x=>x.id===item.id?updated:x)));setNotice('已更新');}catch(e){if(e instanceof ApiClientError&&e.code==='TODO_NOT_FOUND'){setError('该待办已不存在，已重新加载列表');void load();}else setError(e instanceof Error?e.message:'更新失败，请稍后重试');}};
 const remove=async()=>{if(!deleting)return;const item=deleting;setDeleting(null);try{await todoApiClient.remove(item.id);setItems(v=>v.filter(x=>x.id!==item.id));setNotice('已删除');}catch(e){setError(e instanceof Error?e.message:'删除失败，请稍后重试');}};
 return <main><h1>待办清单</h1><form onSubmit={saveNew}><label htmlFor="new-title">新的待办标题</label><div className="new-row"><input id="new-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/><button type="submit">新增</button></div></form>{notice&&<p role="status">{notice}</p>}{error&&<div role="alert">{error} {items.length===0&&<button onClick={()=>void load()}>重新加载</button>}</div>}{loading?<p>正在加载待办…</p>:items.length===0?<p>还没有待办，新增第一条吧。</p>:<ul>{items.map(item=><li key={item.id}>{editing===item.id?<input aria-label="编辑待办标题" autoFocus value={editTitle} onChange={e=>setEditTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){const msg=validateTitle(editTitle);if(msg)setError(msg);else{void update(item,{title:editTitle});setEditing(null);}}if(e.key==='Escape'){setEditing(null);setEditTitle(item.title);}}}/>:<span className={item.completed?'done':''}>{item.title}</span>}<button aria-label={item.completed?'恢复待办':'标记完成'} onClick={()=>void update(item,{completed:!item.completed})}>{item.completed?'恢复':'完成'}</button><button aria-label="编辑待办" onClick={()=>{setEditing(item.id);setEditTitle(item.title);}}>编辑</button><button aria-label="删除待办" onClick={()=>setDeleting(item)}>删除</button></li>)}</ul>}{deleting&&<div role="dialog" aria-modal="true"><p>确定要永久删除“{deleting.title}”吗？</p><button onClick={()=>void remove()}>确认删除</button><button onClick={()=>setDeleting(null)}>取消</button></div>}</main>}
